name          'example42-memcached'
version '3.0.2'
source        'https://github.com/example42/puppet-memcached'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'Puppet module for memcached'
description   'This module installs and manages memcached. Is based on stdmod 0.9.0'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
